language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - extra-android-support
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+ 
before_install:
    - yes | sdkmanager "platforms;android-28"
script:
- ./gradlew build
